token:
  expiration_time: 86400000
  secret: '{cipher}AQAzzCf7OEgs8Put25PKEK2w0qMDL6br8xgiqTBgguNz7zl2Qx5KiHaonDIMx2cG3ooX8uhkhU2MXoCdkrr+wbsSNF1RTvs5xymUzzU7CpUiJkG7R8jEGKGCLhBNihR/yFbPlKYaFi4y7ifWT6sqbGQEWPOFla36LAQXj6TlpoQ7KNLMB1XNj0FtOTjaYef4SWIAO5zCwqtX9eoxNR8s1S3qpsPVwmcCZ3rNikyiUBY50mS2rGjPUhIbJRTnxtYXunudsrMGlzgw1ya0rkGVb61YsJya8AW9quxZwObRcbrGVWn9Xrh5YyVAAPdzgL8i37A4+Jyi0YYcoYoUmGDkypWqMJ3TF7sMlyu/ZCnCRGJgG/JYnmMqYLo7n2kF2QLV0A1Yqv3E/GLYUiuHNHxIfHMY'

gateway:
  ip: 192.168.0.12
