token:
  expiration_time: 86400000
  secret: '{cipher}AQBw4cAAQ62KwCG9j9K/eBm0oxRXNbJgDCn7LjRMoWKJxF9whAn4bm3jXDIDjikT5HyGvxJJTSF9w+aEuwQAq8AP5PKsGP5FkkdrEG4IXEU7dPrjNIvDJTmzMkbcA/L/mO6/OCkcYhTNPrSdyhkymcuADbk8cwjnopjVuYlhRRTTplCvV5zUn0sFZRrsnFRfb93Xv1r4GY+1IpSyQNt/zUg3SbISZiHwxZUimymqQRPu32H7asBPshfa2zurwhg8PXeLmvzuYbysVIHUqbEiUJy2hPxDFioov8/HQv9UiVoZGspnIqsCanOpr7Po37IAnTztjJy6AcB5OwFxVLR7qukryeIniJiSd7QIxrYp8ngj4G2JKVVkooUZem5Rn8RaBH8zL6FkNNaaN33azdPP5Sar'

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username: test
    password: '{cipher}AQCAuAZ+sX0BC3Tx4kJ3psFhXjS1b0UyyaGJZzAft2AIrZv1na7DYeOVWSOmEinC/7QvLr4qdrOJTJnS+9p6YJGYrrFFtEhxr/r4q1EH1mjnePOOQJd1/UuF49YjWSyz9f+KXdNGJXxupKLMw+MtZtvRG7A8ZEqqXYrT2SMaW9lkHkIeIn/we+dPR08DWSdds7Azjmy2FeAgS4IzB9LZyijircruY73a1TAAPU0n+op44O3B8UGE0jnUKWYO4S5j1V0RxRijzZvKcaMJS9xeCs7+c3wGEAM+d7cec/RUUqrP+jxilQjfoRDYcQ918ESp0guzubAEak7idl8KNjD+EhuOBmV5CsJrNHvkYutjTThpqDk9T+pJ96s7FimaaIvcHFQ='
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
          jdbc:
            lob:
              non_contextual_creation: true

gateway:
  ip: 192.168.0.12
