spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: '{cipher}AQBLKj9twONWAAkYDt7NWXdJ5rmYfv3PtM0Q3W2YAXEuSVuASIYD3bECc3tshSV/OijV4CABM6fY2wo6GXxT+2s4XTD5MwhlzpTpP6KBmq6vsiyITkZdVPurpIYfet43YoRiGRZzJFI3jvs61kw7aiK7Xm9jq2nv7DXjKh+yZIJ60Q/GVYoV12ILj2Rd1IX1+0w0n1NpQm4lfWHacmA+AWqsmdkJNWdc2gQZ4eaKSmfq/Eod16auEQXvL0Rh+bRNmdrqdtIumWfwNF7Vo5+q+4RtF3/1L9cFa744oqWR1d5DTPaD1IymMCuPvlpQAPiNslZ2YfdSsKQfxAPlcAe9gAuZsBL8TVuM9C1mFNgMii2Jj+ZnD3v/nNziCmKIjkQ1+T4='

orders:
  url: http://orders/%s/orders
  exception:
    orders_is_empty: User's orders is empty.
