spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCDd4jtL1mHBXUvwetmtqBIy3wfqnoFCaLrtmRZsV1sFmjqNpDHt7bcQpql4elVc8u3/q3xFza/yjyaSJaDM0/dRmPs8sskZEcf7PGv0cYMzpjKBUs03bP3qPeI/Zs7yFbHHB/AVyrzcnVieFRZQ+TN0bgD9IXjqZp8cSi6ynibdaniZOSdhunS6S+AV3mZ1sfP/7Be1NOh7EOkNXxiqcllYHWbz9L3RLsF8t1S/Q1eg+s4l2FtZmABez0XHP56/QID1LA/+A9h7IC1199GszWh97qrBMAcCuUtd+BdV4Vw+CSXjayR7mDQx8AB2AzmkblccBlia1Dk7S0QKZ0I0NHdsTeBCTgfHTB+foJvlkS2uHe38R/MC24+mQVZlk548kk='
