spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: '{cipher}AQCOxseD7HM94BhRWzzXAX1J5wPmQNSoVnYryOwdaQi8dXFvbFtTrtxx7iCKo2dmLz5TrmkDt6Oj1NLxrnhkU1aanESp5acETaLbWhJXFQRe60kuWIqxniYXehXk8Mlns5ffoLKTQNZLeaPzmxqXqlV+mc3b6Jvxzv3WS5t597ZTRmaBz1ojqS59+9snvAchbwtSf6bPFrkSqlnQKp6wI1d6bVd5wy9SmLH6IJ+RglHhv1Xzy8U4a/ywdM1vjkQfuMM7GowuCSAuaBOMCr2+aDOBgE9qtjZ2VzXEojQZ7Q0SfaHnj9ucWgW3cMxzHAR57ScJAO0aGOPdB8oiSxcJTfWr8RNmzURFmvw7rUkvpgx1UH7PBjNR2YLgfb4nIvXUX1M='

orders:
  url: http://orders/%s/orders
  exception:
    orders_is_empty: User's orders is empty.
